# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joshua McLucas - Software Engineer and Theater Artist
email: jtmclucas13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The official portfolio and blog of Joshua McLucas, a Philadelphia-based
  software engineer and theater artist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.joshuamclucas.com" # the base hostname & protocol for your site
twitter_username: joshmclucas

# Build settings
markdown: kramdown
